name = "radical-ssr-wrapper"
main = "src/index.js"
compatibility_date = "2023-11-21"
compatibility_flags = [ "nodejs_compat" ]

[vars]
COLD_MISS_PROB = 0  # The probability that a hit should be treated as a miss due to a cold start
CAP_MISS_PROB = 0   # The probability that a hit should be treated as a miss because the item was evicted from the cache
DO_CONSISTENCY_CHECK = false
DEBUGPRINT = true

[build]
command = "wasm-pack build --target bundler ./src/radical-ssr/ && cp ./src/radical-ssr/wasm-patch.js ./src/radical-ssr/pkg/ssr_bench.js"
watch_dir = ["src"]